### ISSUE TITLE
Voicemeeter goes down

### ISSUE THREAD

**Issue by sjc-or** [SaifAqqad/VMR.ahk#1]
Thanks so much for writing this! I've found it very useful.

Modified the following that allows user to restart Voicemeeter if it goes down while script is running.

/* Original
    IsParametersDirty(){
        return DllCall(VBVMR.VM_DLL . "\VBVMR_IsParametersDirty")
    }
*/
; Modified 2020-10-02
    IsParametersDirty(){
        a:= DllCall(VBVMR.VM_DLL . "\VBVMR_IsParametersDirty")
		if ( a < 0 )
		{
		msgbox Voicemeeter is down, please restart then then press OK
		return 1
		}
		return a
    }

**Comment by SaifAqqad** [comment]
Hey, I'm glad you found it useful :D

I will look into doing something like that, maybe even attempt to restart Voicemeeter before throwing an error to the user

**Comment by sjc-or** [comment]
Yes, for now, I just wanted a prompt without returning to my script for debugging purposes to keep my polling timer from repeating the error on every call. 
 Since my timer doesn't explicitly call IsParametersDirty (it is iterating through getParameter values) I thought this was the best way to fix it for now. I was thinking I could handle any negative returned parameters in my script this way but return from gain can return negative values. 

Actually the API author ( Vincent)  recommended using a call to Voicemeetertype to determine if it Voicemeeter is still running.

Thanks again.  FYI, My application integrates yours with MIDI so I can define my own MIDI controller that can talk in both directions (with LED indicators), that can replace Voicemeeter's MIDI and Macro Mapping. I use an APC-MINI to control many of the functions I'm interested in, instead of the GUI interface for VoiceMeeter Potato.

Thanks again!

**Comment by SaifAqqad** [comment]
I actually pushed a [commit](https://github.com/SaifAqqad/VMR.ahk/commit/645f73071955972dce405b2f8253f19c593e82c1) today that added this prompt
>I was thinking I could handle any negative returned parameters in my script this way but return from gain can return negative values.

Yeah that's the reason I switched to throwing exceptions instead of just returning the negative return values.

> Actually the API author ( Vincent) recommended using a call to Voicemeetertype to determine if it Voicemeeter is still running.

I'll look into that and adjust the methods, thank you :D

> FYI, My application integrates yours with MIDI so I can define my own MIDI controller that can talk in both directions (with LED indicators), that can replace Voicemeeter's MIDI and Macro Mapping. I use an APC-MINI to control many of the functions I'm interested in, instead of the GUI interface for VoiceMeeter Potato.

Wow that sounds way more serious than what I use it for lol
