### ISSUE TITLE
VMR.ahk for ahk v2

### ISSUE THREAD

**Issue by cmsethi** [SaifAqqad/VMR.ahk#17]
Hello, could you please convert the vmr.ahk code to be compatible with ahkv2? Thanks

**Comment by SaifAqqad** [comment]
I'll definitely do an ahkv2 version but it will probably take some time as I have so many other things going on right now

**Comment by NeonLightning** [comment]
hate to pester, and necro. but any chance to look at this since?

**Comment by SaifAqqad** [comment]
I have started working on an ahkv2 port on the [v2 branch](https://github.com/SaifAqqad/VMR.ahk/tree/v2) but it's still a **_very_** early wip.

Right now, the only (fully) working part is the `VBVMR` class

**Comment by SaifAqqad** [comment]
v2 is fully done 😊

Some parts of the docs need some work though (there are some formatting issues, and missing examples), will get to it next week.
