### ISSUE TITLE
Release version 1.1.0 with ahkpm support?

### ISSUE THREAD

**Issue by joshuacc** [SaifAqqad/VMR.ahk#18]
Hi @SaifAqqad. Thanks so much for adding ahkpm support to this library!

I was just playing around with generating an ahkpm demo using the VMR.ahk package and noticed that while there is a version 1.0.0 tagged, there hasn't been a new version released since you added ahkpm support.

That means that when users install via ahkpm, they'll get 1.0.0, but when they try to use `ahkpm include`, they'll get an error about VMR.ahk not having an ahkpm.json file.

**Comment by SaifAqqad** [comment]
Hmm, I will create a new tag then

Thanks for the heads up

**Comment by SaifAqqad** [comment]
I have pushed a new [tag](https://github.com/SaifAqqad/VMR.ahk/releases/tag/1.1.0), and I tried testing it on my [other repo](https://github.com/SaifAqqad/AHK_MicMute) but I encountered a problem, I have my main ahk file inside a `src` folder but the ahkpm.json is in the repo's root folder, this caused the `#include` path to be wrong 

![image](https://user-images.githubusercontent.com/47293197/204101252-f72ad708-7d2b-497b-927a-0584c4ffaf62.png)

This should be `%A_ScriptDir%\..\ahkpm-modules\github.com\SaifAqqad\VMR.ahk\dist\VMR.ahk`

I will create an issue for this on your repo shortly
