### ISSUE TITLE
Using Gain Layer 

### ISSUE THREAD

**Issue by Zormm** [SaifAqqad/VMR.ahk#19]
I noticed that a few new Parameters were added to the Voicemeeter Remote API as of November 2022 with the new Version 3. One of them being the GainLayer Input Strip Parameter. 
Is there any Way of making use of this Parameter in the current state of vmr.ahk?
The setParameter function does not work as far as I can tell because the GainLayer itself needs the Parameter of the desired Bus AND the desired gain which cannot be accomplished.

I would much appreciate any solution to using GainLayer in vmr.ahk
Thanks in Advance

From the Documentation of the Remote API:
![image](https://user-images.githubusercontent.com/98342891/212924117-0e1e4a70-3f72-4377-89ee-cf11213d749f.png)

**Comment by SaifAqqad** [comment]
Did you try setParameter like this: `vmr.strip[3].setParameter("GainLayer[0]", -10)`?

I'm still going to add the parameters, but setParameter should work as well.

**Comment by Zormm** [comment]
I didn't think of doing it like that. Thank You!
