### ISSUE TITLE
Strips UI

### ISSUE THREAD

**Issue by cmsethi** [SaifAqqad/VMR.ahk#20]
May i make a request? Can you make the Strips UI in ahk v1 the way you made the buses(UI)?
I tried (Voicemeeter Compact) by Onyx and Iris in Python, but it takes almost 10% of CPU whereas ahk takes only 1 or 1.5%.
I'm also using Cantabile to run the vst plugins along with Voicemeeter that also takes some percentage of the CPU.
look forward to hearing from you.
edit:
I tried and made it. (Strip UI), ### Thanks
regards

**Comment by SaifAqqad** [comment]
It can be done easily by replacing occurrences of `vm.bus` with `vm.strip`.

**Comment by cmsethi** [comment]
Yes, I did it that way, thanks, but I'm using two separate scripts, couldn't make it into one GUI, got duplicate function errors. If you can help me with that, it would be great.
regards

**Comment by SaifAqqad** [comment]
```ahk
#Include, %A_ScriptDir%\..\dist\VMR.ahk
SetBatchLines, 20ms

Global vm, GUI_hwnd, is_win_pos_changing:=0

vm := new VMR().login()
showUI()
vm.onUpdateLevels:= Func("syncLevel") ; register level callback func
vm.onUpdateParameters:= Func("syncParameters") ; register params callback func
OnMessage(0x46, Func("onPosChanging"))

showUI(){
    Global
    Gui, vm:New, +HwndGUI_hwnd, VoiceMeeter Remote UI
    xPos:=10
    Loop % vm.bus.Length() { ; add UI controls for each bus
        ;bus title
        yPos:=0, funcObj:=""
        Gui, Add, Text, x%xPos% y%yPos% w100, % vm.bus[A_Index].name

        ;bus level
        yPos+= 30
        Gui, Add, Progress, x%xPos% y%yPos% w20 h200 Range-72-20 c0x70C399 Background0x2C3D4D vertical Hwndbus_%A_Index%_level

        ;bus gain
        yPos+= 220
        Gui, Add, Edit, w50 x%xPos% y%yPos% ReadOnly
        Gui, Add, UpDown,Hwndbus_%A_Index%_gain Range-60-12 x0
        funcObj:= Func("updateParam").bind("bus", "gain", A_Index)
        GuiControl +g, % bus_%A_Index%_gain, % FuncObj

        ;bus mute
        yPos+= 30
        Gui, Add, CheckBox, x%xPos% y%yPos% Hwndbus_%A_Index%_mute, Mute
        funcObj:= Func("updateParam").bind("bus", "mute", A_Index)
        GuiControl +g, % bus_%A_Index%_mute, % FuncObj

        ;bus device
        if(vm.bus[A_Index].isPhysical()){ ; make sure the bus is a physical one (eg. 1-3 in banana)
            yPos+= 30
            Gui, Add, DropDownList, x%xPos% y%yPos% Hwndbus_%A_Index%_device
            funcObj:= Func("updateParam").bind("bus", "device", A_Index)
            GuiControl +g, % bus_%A_Index%_device, % FuncObj
            refreshDevices("bus", A_Index)
        }

        xPos+=150
    }

    ; strips
    xPos:=10
    Loop % vm.strip.Length() { ; add UI controls for each strip
        ;strip title
        yPos:=400, funcObj:=""
        Gui, Add, Text, x%xPos% y%yPos% w100, % vm.strip[A_Index].name

        ;strip level
        yPos+= 30
        Gui, Add, Progress, x%xPos% y%yPos% w20 h200 Range-72-20 c0x70C399 Background0x2C3D4D vertical Hwndstrip_%A_Index%_level

        ;strip gain
        yPos+= 220
        Gui, Add, Edit, w50 x%xPos% y%yPos% ReadOnly
        Gui, Add, UpDown,Hwndstrip_%A_Index%_gain Range-60-12 x0
        funcObj:= Func("updateParam").bind("strip", "gain", A_Index)
        GuiControl +g, % strip_%A_Index%_gain, % FuncObj

        ;strip mute
        yPos+= 30
        Gui, Add, CheckBox, x%xPos% y%yPos% Hwndstrip_%A_Index%_mute, Mute
        funcObj:= Func("updateParam").bind("strip", "mute", A_Index)
        GuiControl +g, % strip_%A_Index%_mute, % FuncObj

        ;strip device
        if(vm.strip[A_Index].isPhysical()){ ; make sure the bus is a physical one (eg. 1-3 in banana)
            yPos+= 30
            Gui, Add, DropDownList, x%xPos% y%yPos% Hwndstrip_%A_Index%_device
            funcObj:= Func("updateParam").bind("strip", "device", A_Index)
            GuiControl +g, % strip_%A_Index%_device, % FuncObj
            refreshDevices("strip", A_Index)
        }

        xPos+=150
    }
    syncParameters() ; get initial values for gui controls
    Gui, Show, H750, VoiceMeeter Remote UI
}

; update vm bus parameters when they change on the AHK UI
updateParam(type, param, index){
    GuiControlGet, val,,% %type%_%index%_%param%
    if(param == "device"){
        RegExMatch(val, "iO)(?<driver>\w+): (?<name>.+)", match)
        if(match)
            vm[type][index].device[match.driver]:= match.name
        else
            vm[type][index].device:= ""
    }else{
        vm[type][index][param]:= val
    }
    SetTimer, syncParameters, -500 ; make sure params are in sync
}

; sync AHK UI controls with vm bus parameters
syncParameters(){
    Loop % vm.bus.Length() {
        GuiControl,, % bus_%A_Index%_gain, % vm.bus[A_Index].gain
        GuiControl,, % bus_%A_Index%_mute, % Format("{:i}", vm.bus[A_Index].mute) ; convert 0.0/1.0 to 0/1
        if(vm.bus[A_Index].__isPhysical())
            refreshDevices("bus", A_Index)
    }

    Loop % vm.strip.Length() {
        GuiControl,, % strip_%A_Index%_gain, % vm.strip[A_Index].gain
        GuiControl,, % strip_%A_Index%_mute, % Format("{:i}", vm.strip[A_Index].mute) ; convert 0.0/1.0 to 0/1
        if(vm.strip[A_Index].__isPhysical())
            refreshDevices("strip", A_Index)
    }
}

; sync level meters with vm bus levels
syncLevel(){
    if(is_win_pos_changing) ;dont update levels if the window is changing its position
        return
    Loop % vm.bus.Length() {
        GuiControl,, % bus_%A_Index%_level, % Max(vm.bus[A_Index].level*) ; get peak level for the bus
    }
    Loop % vm.strip.Length() {
        GuiControl,, % strip_%A_Index%_level, % Max(vm.strip[A_Index].level*) ; get peak level for the bus
    }
}

; clears the bus's drop-down and reinserts the devices
refreshDevices(type, index){
    elems:="| |" ; extra empty element for removing the device
    preSelected:= vm[type][index].device ; get the pre-selected device
    funcName:= "get" type "Devices"
    for i, device in vm[funcName]() {
        elems.= Format("{:U}: {}", device.driver, device.name)
        elems.= device.name == preSelected? "||" : "|"
    }
    GuiControl,, % %type%_%index%_device, % elems
}

vmGuiClose(){
    ExitApp
}

onPosChanging(){
    is_win_pos_changing:=1
    SetTimer, onPosChanged, -50
}

onPosChanged(){
    is_win_pos_changing:=0
}
```

**Comment by cmsethi** [comment]
Thanks for making  the app for me, I'm touched.
when login with these linesGlobal vm, GUI_hwnd, is_win_pos_changing:=0
vm := new VMR().login()

the commands like; voicemeeter.strip[5].A3 := 1, have stopped working.

but when login with these lines:
Global vm, GUI_hwnd, is_win_pos_changing:=0
Global voicemeeter := (new VMR).login()
only commands work.
hereby, I'm attaching the two scripts which works fine separately.

bus/es progress  work with:
Global vm, GUI_hwnd, is_win_pos_changing:=0Global voicemeeter := (new VMR).login()


strip/s progress works with:
Global vm, GUI_hwnd, is_win_pos_changing:=0
vm := (new VMR).login(

chander mohan 

    On Friday, 4 August, 2023 at 08:40:49 pm IST, Saif Alaqqad ***@***.***> wrote:  
 
 

#Include, %A_ScriptDir%\..\dist\VMR.ahk
SetBatchLines, 20ms

Global vm, GUI_hwnd, is_win_pos_changing:=0

vm := new VMR().login()
showUI()
vm.onUpdateLevels:= Func("syncLevel") ; register level callback func
vm.onUpdateParameters:= Func("syncParameters") ; register params callback func
OnMessage(0x46, Func("onPosChanging"))

showUI(){
    Global
    Gui, vm:New, +HwndGUI_hwnd, VoiceMeeter Remote UI
    xPos:=10
    Loop % vm.bus.Length() { ; add UI controls for each bus
        ;bus title
        yPos:=0, funcObj:=""
        Gui, Add, Text, x%xPos% y%yPos% w100, % vm.bus[A_Index].name

        ;bus level
        yPos+= 30
        Gui, Add, Progress, x%xPos% y%yPos% w20 h200 Range-72-20 c0x70C399 Background0x2C3D4D vertical Hwndbus_%A_Index%_level

        ;bus gain
        yPos+= 220
        Gui, Add, Edit, w50 x%xPos% y%yPos% ReadOnly
        Gui, Add, UpDown,Hwndbus_%A_Index%_gain Range-60-12 x0
        funcObj:= Func("updateParam").bind("bus", "gain", A_Index)
        GuiControl +g, % bus_%A_Index%_gain, % FuncObj

        ;bus mute
        yPos+= 30
        Gui, Add, CheckBox, x%xPos% y%yPos% Hwndbus_%A_Index%_mute, Mute
        funcObj:= Func("updateParam").bind("bus", "mute", A_Index)
        GuiControl +g, % bus_%A_Index%_mute, % FuncObj

        ;bus device
        if(vm.bus[A_Index].isPhysical()){ ; make sure the bus is a physical one (eg. 1-3 in banana)
            yPos+= 30
            Gui, Add, DropDownList, x%xPos% y%yPos% Hwndbus_%A_Index%_device
            funcObj:= Func("updateParam").bind("bus", "device", A_Index)
            GuiControl +g, % bus_%A_Index%_device, % FuncObj
            refreshDevices("bus", A_Index)
        }

        xPos+=150
    }

    ; strips
    xPos:=10
    Loop % vm.strip.Length() { ; add UI controls for each strip
        ;strip title
        yPos:=400, funcObj:=""
        Gui, Add, Text, x%xPos% y%yPos% w100, % vm.strip[A_Index].name

        ;strip level
        yPos+= 30
        Gui, Add, Progress, x%xPos% y%yPos% w20 h200 Range-72-20 c0x70C399 Background0x2C3D4D vertical Hwndstrip_%A_Index%_level

        ;strip gain
        yPos+= 220
        Gui, Add, Edit, w50 x%xPos% y%yPos% ReadOnly
        Gui, Add, UpDown,Hwndstrip_%A_Index%_gain Range-60-12 x0
        funcObj:= Func("updateParam").bind("strip", "gain", A_Index)
        GuiControl +g, % strip_%A_Index%_gain, % FuncObj

        ;strip mute
        yPos+= 30
        Gui, Add, CheckBox, x%xPos% y%yPos% Hwndstrip_%A_Index%_mute, Mute
        funcObj:= Func("updateParam").bind("strip", "mute", A_Index)
        GuiControl +g, % strip_%A_Index%_mute, % FuncObj

        ;strip device
        if(vm.strip[A_Index].isPhysical()){ ; make sure the bus is a physical one (eg. 1-3 in banana)
            yPos+= 30
            Gui, Add, DropDownList, x%xPos% y%yPos% Hwndstrip_%A_Index%_device
            funcObj:= Func("updateParam").bind("strip", "device", A_Index)
            GuiControl +g, % strip_%A_Index%_device, % FuncObj
            refreshDevices("strip", A_Index)
        }

        xPos+=150
    }
    syncParameters() ; get initial values for gui controls
    Gui, Show, H750, VoiceMeeter Remote UI
}

; update vm bus parameters when they change on the AHK UI
updateParam(type, param, index){
    GuiControlGet, val,,% %type%_%index%_%param%
    if(param == "device"){
        RegExMatch(val, "iO)(?<driver>\w+): (?<name>.+)", match)
        if(match)
            vm[type][index].device[match.driver]:= match.name
        else
            vm[type][index].device:= ""
    }else{
        vm[type][index][param]:= val
    }
    SetTimer, syncParameters, -500 ; make sure params are in sync
}

; sync AHK UI controls with vm bus parameters
syncParameters(){
    Loop % vm.bus.Length() {
        GuiControl,, % bus_%A_Index%_gain, % vm.bus[A_Index].gain
        GuiControl,, % bus_%A_Index%_mute, % Format("{:i}", vm.bus[A_Index].mute) ; convert 0.0/1.0 to 0/1
        if(vm.bus[A_Index].__isPhysical())
            refreshDevices("bus", A_Index)
    }

    Loop % vm.strip.Length() {
        GuiControl,, % strip_%A_Index%_gain, % vm.strip[A_Index].gain
        GuiControl,, % strip_%A_Index%_mute, % Format("{:i}", vm.strip[A_Index].mute) ; convert 0.0/1.0 to 0/1
        if(vm.strip[A_Index].__isPhysical())
            refreshDevices("strip", A_Index)
    }
}

; sync level meters with vm bus levels
syncLevel(){
    if(is_win_pos_changing) ;dont update levels if the window is changing its position
        return
    Loop % vm.bus.Length() {
        GuiControl,, % bus_%A_Index%_level, % Max(vm.bus[A_Index].level*) ; get peak level for the bus
    }
    Loop % vm.strip.Length() {
        GuiControl,, % strip_%A_Index%_level, % Max(vm.strip[A_Index].level*) ; get peak level for the bus
    }
}

; clears the bus's drop-down and reinserts the devices
refreshDevices(type, index){
    elems:="| |" ; extra empty element for removing the device
    preSelected:= vm[type][index].device ; get the pre-selected device
    funcName:= "get" type "Devices"
    for i, device in vm[funcName]() {
        elems.= Format("{:U}: {}", device.driver, device.name)
        elems.= device.name == preSelected? "||" : "|"
    }
    GuiControl,, % %type%_%index%_device, % elems
}

vmGuiClose(){
    ExitApp
}

onPosChanging(){
    is_win_pos_changing:=1
    SetTimer, onPosChanged, -50
}

onPosChanged(){
    is_win_pos_changing:=0
}

**Comment by cmsethi** [comment]
hi, 
I changed  voicemeeter.strip[5].A3 := 1 to
vm.strip[5].A3 := 1

and now all the commands are working.

thanks for helping me.
regards
chander mohan 

    On Friday, 4 August, 2023 at 08:40:49 pm IST, Saif Alaqqad ***@***.***> wrote:  
 
 

#Include, %A_ScriptDir%\..\dist\VMR.ahk
SetBatchLines, 20ms

Global vm, GUI_hwnd, is_win_pos_changing:=0

vm := new VMR().login()
showUI()
vm.onUpdateLevels:= Func("syncLevel") ; register level callback func
vm.onUpdateParameters:= Func("syncParameters") ; register params callback func
OnMessage(0x46, Func("onPosChanging"))

showUI(){
    Global
    Gui, vm:New, +HwndGUI_hwnd, VoiceMeeter Remote UI
    xPos:=10
    Loop % vm.bus.Length() { ; add UI controls for each bus
        ;bus title
        yPos:=0, funcObj:=""
        Gui, Add, Text, x%xPos% y%yPos% w100, % vm.bus[A_Index].name

        ;bus level
        yPos+= 30
        Gui, Add, Progress, x%xPos% y%yPos% w20 h200 Range-72-20 c0x70C399 Background0x2C3D4D vertical Hwndbus_%A_Index%_level

        ;bus gain
        yPos+= 220
        Gui, Add, Edit, w50 x%xPos% y%yPos% ReadOnly
        Gui, Add, UpDown,Hwndbus_%A_Index%_gain Range-60-12 x0
        funcObj:= Func("updateParam").bind("bus", "gain", A_Index)
        GuiControl +g, % bus_%A_Index%_gain, % FuncObj

        ;bus mute
        yPos+= 30
        Gui, Add, CheckBox, x%xPos% y%yPos% Hwndbus_%A_Index%_mute, Mute
        funcObj:= Func("updateParam").bind("bus", "mute", A_Index)
        GuiControl +g, % bus_%A_Index%_mute, % FuncObj

        ;bus device
        if(vm.bus[A_Index].isPhysical()){ ; make sure the bus is a physical one (eg. 1-3 in banana)
            yPos+= 30
            Gui, Add, DropDownList, x%xPos% y%yPos% Hwndbus_%A_Index%_device
            funcObj:= Func("updateParam").bind("bus", "device", A_Index)
            GuiControl +g, % bus_%A_Index%_device, % FuncObj
            refreshDevices("bus", A_Index)
        }

        xPos+=150
    }

    ; strips
    xPos:=10
    Loop % vm.strip.Length() { ; add UI controls for each strip
        ;strip title
        yPos:=400, funcObj:=""
        Gui, Add, Text, x%xPos% y%yPos% w100, % vm.strip[A_Index].name

        ;strip level
        yPos+= 30
        Gui, Add, Progress, x%xPos% y%yPos% w20 h200 Range-72-20 c0x70C399 Background0x2C3D4D vertical Hwndstrip_%A_Index%_level

        ;strip gain
        yPos+= 220
        Gui, Add, Edit, w50 x%xPos% y%yPos% ReadOnly
        Gui, Add, UpDown,Hwndstrip_%A_Index%_gain Range-60-12 x0
        funcObj:= Func("updateParam").bind("strip", "gain", A_Index)
        GuiControl +g, % strip_%A_Index%_gain, % FuncObj

        ;strip mute
        yPos+= 30
        Gui, Add, CheckBox, x%xPos% y%yPos% Hwndstrip_%A_Index%_mute, Mute
        funcObj:= Func("updateParam").bind("strip", "mute", A_Index)
        GuiControl +g, % strip_%A_Index%_mute, % FuncObj

        ;strip device
        if(vm.strip[A_Index].isPhysical()){ ; make sure the bus is a physical one (eg. 1-3 in banana)
            yPos+= 30
            Gui, Add, DropDownList, x%xPos% y%yPos% Hwndstrip_%A_Index%_device
            funcObj:= Func("updateParam").bind("strip", "device", A_Index)
            GuiControl +g, % strip_%A_Index%_device, % FuncObj
            refreshDevices("strip", A_Index)
        }

        xPos+=150
    }
    syncParameters() ; get initial values for gui controls
    Gui, Show, H750, VoiceMeeter Remote UI
}

; update vm bus parameters when they change on the AHK UI
updateParam(type, param, index){
    GuiControlGet, val,,% %type%_%index%_%param%
    if(param == "device"){
        RegExMatch(val, "iO)(?<driver>\w+): (?<name>.+)", match)
        if(match)
            vm[type][index].device[match.driver]:= match.name
        else
            vm[type][index].device:= ""
    }else{
        vm[type][index][param]:= val
    }
    SetTimer, syncParameters, -500 ; make sure params are in sync
}

; sync AHK UI controls with vm bus parameters
syncParameters(){
    Loop % vm.bus.Length() {
        GuiControl,, % bus_%A_Index%_gain, % vm.bus[A_Index].gain
        GuiControl,, % bus_%A_Index%_mute, % Format("{:i}", vm.bus[A_Index].mute) ; convert 0.0/1.0 to 0/1
        if(vm.bus[A_Index].__isPhysical())
            refreshDevices("bus", A_Index)
    }

    Loop % vm.strip.Length() {
        GuiControl,, % strip_%A_Index%_gain, % vm.strip[A_Index].gain
        GuiControl,, % strip_%A_Index%_mute, % Format("{:i}", vm.strip[A_Index].mute) ; convert 0.0/1.0 to 0/1
        if(vm.strip[A_Index].__isPhysical())
            refreshDevices("strip", A_Index)
    }
}

; sync level meters with vm bus levels
syncLevel(){
    if(is_win_pos_changing) ;dont update levels if the window is changing its position
        return
    Loop % vm.bus.Length() {
        GuiControl,, % bus_%A_Index%_level, % Max(vm.bus[A_Index].level*) ; get peak level for the bus
    }
    Loop % vm.strip.Length() {
        GuiControl,, % strip_%A_Index%_level, % Max(vm.strip[A_Index].level*) ; get peak level for the bus
    }
}

; clears the bus's drop-down and reinserts the devices
refreshDevices(type, index){
    elems:="| |" ; extra empty element for removing the device
    preSelected:= vm[type][index].device ; get the pre-selected device
    funcName:= "get" type "Devices"
    for i, device in vm[funcName]() {
        elems.= Format("{:U}: {}", device.driver, device.name)
        elems.= device.name == preSelected? "||" : "|"
    }
    GuiControl,, % %type%_%index%_device, % elems
}

vmGuiClose(){
    ExitApp
}

onPosChanging(){
    is_win_pos_changing:=1
    SetTimer, onPosChanged, -50
}

onPosChanged(){
    is_win_pos_changing:=0
}
