### ISSUE TITLE
Recorder Loading issues

### ISSUE THREAD

**Issue by zaregg** [SaifAqqad/VMR.ahk#5]
Hi, I am trying to load an mp3 file, but it gives me this error. I don't really know if I did something wrong but maybe it's a bug. I figured out that the same error occurs when I don't put in anything at all, so this could just be me fucking up but I am certain that the file is in that location and I've checked it multiple times, but yea it still could be lol

#### Error:
![image](https://user-images.githubusercontent.com/57303863/111228735-fbe41a80-85e4-11eb-83da-0134da04006f.png)
#### This is the file i want to load
![image](https://user-images.githubusercontent.com/57303863/111228640-d22af380-85e4-11eb-908d-f7403c600ac7.png)

#### The part of my code that crashes
```autohotkey
voicemeeter := new VMR()
voicemeeter.login()

voicemeeter.recorder["mode.PlayOnLoad"]:= true

voicemeeter.recorder.load:= "D:\Music\Trance-Music-for-Racing-Game.mp3"

```
#### This is where the error occurs
```autohotkey
SetParameterString(p_prefix, p_parameter, p_value){
        this.IsParametersDirty()
        errLevel := DllCall(VBVMR.FUNC_ADDR["SetParameterString" . VBVMR.STR_TYPE], "AStr", p_prefix . "." . p_parameter , VBVMR.STR_TYPE . "Str" , p_value , "Int")
        if (errLevel<0)
            Throw, Format("`nVBVMR_SetParameterString returned {}`nDllCall returned {}", errLevel, ErrorLevel)
        return p_value
}

GetParameterFloat(p_prefix, p_parameter){
        local value
        this.IsParametersDirty()
        VarSetCapacity(value, 4)
        errLevel := DllCall(VBVMR.FUNC_ADDR.GetParameterFloat, "AStr" , p_prefix . "." . p_parameter , "Ptr" , &value, "Int")
        if (errLevel<0)
            Throw, Format("`nVBVMR_GetParameterFloat returned {}`nDllCall returned {}", errLevel, ErrorLevel)
        value := NumGet(&value, 0, "Float")
        return value
    }
```

**Comment by SaifAqqad** [comment]
Thanks for reporting, this is indeed a bug with VMR, but it should be an easy fix.

The recorder object is not handling string parameters at all, as its using `setParameterFloat` for all parameters, thats why it's failing.

**Comment by SaifAqqad** [comment]
Should be all fixed now :D

**Comment by zaregg** [comment]
Thank u :D Great Library btw!

**Comment by SaifAqqad** [comment]
This is unrelated to VMR.
In AHK, If you want to access global variables inside functions you need to add `global` to the top of the function like this 
```ahk
PlaySound() {
    global
    voicemeeter.recorder.load:= "D:\Music\There he is! There's my favorite white boy!.mp3"
}
```

or just declare the VMR object as a [super-global variable](https://www.autohotkey.com/docs/Functions.htm#SuperGlobal)
```ahk
global voicemeeter := new VMR()
```

if you use vscode install [this extension](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-autohotkey-plus) and use the debugger that's included with it, it will help you alot
![image](https://user-images.githubusercontent.com/47293197/111281157-4dbc8d00-8645-11eb-98ea-3706a111ef31.png)

**Comment by zaregg** [comment]
Thank you a lot!!
