### ISSUE TITLE
 voicemeeter.command.lock() is missing

### ISSUE THREAD

**Issue by Glaived** [SaifAqqad/VMR.ahk#9]
> 2-REMOTE API: Command.Lock function allow to lock/unlock GUI (like Menu option).

https://forum.vb-audio.com/viewtopic.php?p=5739&sid=e42f1b27d8b6d94ea1833632218cb630#p5739

I don't know if the parameter is accessible in read mode (Get)

**Comment by SaifAqqad** [comment]
commit ef2e009 Added the new commands
and 940a387 added them to the [docs](https://saifaqqad.github.io/VMR.ahk/#/VMR-Class/command-object?id=lockstate)
